import {
  NARROW_TAG_TEXT_DISPLAY_LENGTH,
  SHARE_DESCRIPTION,
  SHARE_SUCCESS_MESSAGE,
  SHARE_ERROR_MESSAGE,
} from 'common/constants'

export const MESSAGE_DISPLAY_LENGTH = 125;

export {
  NARROW_TAG_TEXT_DISPLAY_LENGTH,
  SHARE_DESCRIPTION,
  SHARE_SUCCESS_MESSAGE,
  SHARE_ERROR_MESSAGE,
}
